import product1 from "./assets/products/1.png";
import product2 from "./assets/products/2.png";
import product3 from "./assets/products/3.png";

export const PRODUCTS = [
  {
    id: 1,
    name: "Black Polo",
    price:250,
    productImage:product1,
    type:"Polo",
    gender:"Men",
    color:"Black",
    quantity:3,

  },
  {
    id: 2,
    name: "Blue Polo",
    price:350,
    productImage:product1,
    type:"Polo",
    gender:"Women",
    color:"Blue",
    quantity:3,
  },
  {
    id: 3,
    name: "Black Hoodie",
    price:500,
    productImage:product2,
    type:"Hoodie",
    gender:"Men",
    color:"Black",
    quantity:2,
  },
  {
    id: 4,
    name: "Pink Polo",
    price:350,
    productImage:product1,
    type:"Polo",
    gender:"Women",
    color:"Pink",
    quantity:6,
  },
  {
    id: 5,
    name: "Green Polo",
    price:250,
    productImage:product1,
    type:"Polo",
    gender:"Men",
    color:"Green",
    quantity:1,
  },
  {
    id: 6,
    name: "Green Polo",
    price:250,
    productImage:product1,
    type:"Polo",
    gender:"Women",
    color:"Green",
    quantity:1,
  },
  {
    id: 7,
    name: "Blue Hoodie",
    price:500,
    productImage:product2,
    type:"Hoodie",
    gender:"Women",
    color:"Blue",
    quantity:2,
  },
  {
    id: 8,
    name: "Black Hoodie",
    price:500,
    productImage:product2,
    type:"Hoodie",
    gender:"Women",
    color:"Black",
    quantity:5,
  },
  {
    id: 9,
    name: "Blue Round",
    price:300,
    productImage:product3,
    type:"Basic",
    gender:"Men",
    color:"Black",
    quantity:2,
  },
  {
    id: 10,
    name: "Red Round",
    price:300,
    productImage:product3,
    type:"Basic",
    gender:"Women",
    color:"Red",
    quantity:2,
  },
  {
    id: 11,
    name: "Grey Round",
    type: "Basic",
    productImage:product3,
    price: 300,
    color: "Grey",
    gender: "Men",
    quantity: 1,
  },
  {
    id: 12,
    name: "Purple Hoodie",
    type: "Hoodie",
    productImage:product2,
    price: 500,
    color: "Purple",
    gender: "Women",
    quantity: 3,
  },
  {
    id: 13,
    name: "Grey Round",
    type: "Basic",
    price: 300,
    productImage:product3,
    color: "Grey",
    gender: "Women",
    quantity: 1,
  },
  {
    id: 14,
    name: "White Round",
    type: "Basic",
    price: 300,
    productImage:product3,
    color: "White",
    gender: "Women",
    quantity: 0
  },
  {
    id: 15,
    name: "Black Round",
    type: "Basic",
    price: 300,
    color: "Black",
    gender: "Men",
    quantity: 7,
    productImage:product3,

  },
  {
    id: 16,
    name: "Purple Round",
    type: "Basic",
    price: 300,
    color: "Purple",
    gender: "Men",
    quantity: 1,
    productImage:product3,

  },
  {
    id: 17,
    name: "White Round",
    type: "Basic",
    price: 300,
    color: "White",
    gender: "Men",
    quantity: 2,
    productImage:product3,
  },
  {
    id: 18,
    name: "Blue Round",
    type: "Basic",
    price: 300,
    color: "Blue",
    gender: "Women",
    quantity: 3,
    productImage:product3,
  },
  {
    id: 19,
    name: "Yellow Hoodie",
    type: "Hoodie",
    price: 500,
    color: "Yellow",
    gender: "Women",
    quantity: 1,
    productImage:product2,

  },
  {
    id: 20,
    name: "White Polo",
    type: "Polo",
    price: 350,
    color: "White",
    gender: "Women",
    quantity: 4,
    productImage:product1,

  },
  {
    id: 21,
    name: "Red Polo",
    type: "Polo",
    price: 250,
    color: "Red",
    gender: "Men",
    quantity: 2,
    productImage:product1,

  },
  {
    id: 22,
    name: "Blue Hoodie",
    type: "Hoodie",
    price: 500,
    color: "Blue",
    gender: "Men",
    quantity: 0,
    productImage:product2,

  },
  {
    id: 23,
    name: "Grey Hoodie",
    type: "Hoodie",
    price: 500,
    color: "Grey",
    gender: "Men",
    quantity: 2,
    productImage:product2,
  },
  {
    id: 24,
    name: "Grey Polo",
    type: "Polo",
    price: 300,
    color: "Grey",
    gender: "Men",
    quantity: 3,
    productImage:product1,

  },
  {
    id: 25,
    name: "Red Hoodie",
    type: "Hoodie",
    price: 300,
    color: "Red",
    gender: "Men",
    quantity: 0,
    productImage:product2,
  },
  {
    id: 26,
    name: "White Polo",
    type: "Polo",
    price: 300,
    color: "White",
    gender: "Men",
    quantity: 1,
    productImage:product1,
  },
  {
    id: 27,
    name: "White Hoodie",
    type: "Hoodie",
    price: 500,
    color: "White",
    gender: "Women",
    quantity: 3,
    productImage:product2,
  },
  {
    id: 28,
    name: "Grey Round",
    type: "Basic",
    price: 300,
    color: "Grey",
    gender: "Men",
    quantity: 0,
    productImage:product3,
  },
  {
    id: 29,
    name: "Black Round",
    type: "Basic",
    price: 300,
    color: "Black",
    gender: "Women",
    quantity: 0,
    productImage:product3,
  },
  {
    id: 30,
    name: "Black Polo",
    type: "Polo",
    price: 300,
    color: "Black",
    gender: "Women",
    quantity: 4,
    productImage:product1,
  },
];
